[package]
name = "mctp-estack"
description = "Embedded MCTP stack"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/CodeConstruct/mctp-rs"
categories = ["network-programming", "embedded", "hardware-support", "no-std"]

[dependencies]
mctp = { path = "../mctp", default-features = false }
libmctp = { workspace = true }
heapless = "0.8"
log = { version = "0.4", optional = true }
crc = "3"
embedded-io-async = { workspace = true }
defmt = { workspace = true, optional = true }
embassy-sync = "0.6"
embassy-futures = "0.1"
smbus-pec = { version = "1.0", features = ["lookup-table"] }
uuid = { version = "1.16.0", default-features = false }

[features]
default = ["log"]
std = ["mctp/std"]
log = ["dep:log"]
defmt = ["mctp/defmt", "dep:defmt" ]

[dev-dependencies]
proptest = "1.0.0"
embedded-io-adapters = { workspace = true, features = ["std", "futures-03"] }
simplelog = "0.12"
env_logger = "0.11"
smol = "2.0"
